import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

/**
 * Gemini permission sandboxing (decision #9, headless-automation plan). Gemini's CLI (checked
 * against the installed 0.58.0, not the harness's older `lib/ai/gemini.sh` comment written against
 * 0.56.0's now-deprecated JSON `coreTools`/`excludeTools` mechanism) uses a TOML policy engine
 * instead, loaded from tiered directories (Default -> Extension -> Workspace -> User -> Admin,
 * highest priority wins). The per-worktree Workspace tier is currently non-functional
 * (gemini-cli issue #18186), so this is written once to the **User** tier
 * (`~/.gemini/policies/ai-intake-mcp-headless.toml`, machine-global) rather than per-project —
 * additive alongside anything else already in that directory, never a replacement.
 *
 * Every rule sets `interactive = false` so this never affects your own interactive Gemini sessions
 * — only headless automation runs are sandboxed by it.
 */

const DEFAULT_POLICY_PATH = join(homedir(), ".gemini", "policies", "ai-intake-mcp-headless.toml");

interface DenyRule {
  toolName: string;
  commandPrefix: string;
}

/** A deliberately narrow starting deny-list — no git push, no publishing/deploying — matching the
 * decision's "no git push, no deploy commands, etc." Extend here if a real headless run turns out
 * to need more. */
const DENY_RULES: DenyRule[] = [
  { toolName: "run_shell_command", commandPrefix: "git push" },
  { toolName: "run_shell_command", commandPrefix: "npm publish" },
  { toolName: "run_shell_command", commandPrefix: "docker push" },
  { toolName: "run_shell_command", commandPrefix: "kubectl apply" },
  { toolName: "run_shell_command", commandPrefix: "terraform apply" },
  { toolName: "run_shell_command", commandPrefix: "terraform destroy" },
];

export function buildGeminiPolicyToml(): string {
  const header =
    "# Auto-generated by ai-intake-mcp — headless automation permission profile (decision #9).\n" +
    "# User-tier policy file; Workspace-tier is currently non-functional (gemini-cli issue #18186),\n" +
    "# so this applies machine-wide. Every rule sets interactive = false so it never affects your own\n" +
    "# interactive Gemini sessions — only headless automation runs are sandboxed by it.\n";

  const rules = DENY_RULES.map(
    (rule) =>
      `[[rule]]\n` +
      `toolName = "${rule.toolName}"\n` +
      `commandPrefix = "${rule.commandPrefix}"\n` +
      `decision = "deny"\n` +
      `priority = 100\n` +
      `interactive = false\n`,
  ).join("\n");

  return `${header}\n${rules}`;
}

/** Writes the policy file to `destPath` (default: the real `~/.gemini/policies/...` User-tier
 * path). Idempotent — safe to call on every automation startup, not just once. */
export function syncGeminiPolicy(destPath: string = DEFAULT_POLICY_PATH): { path: string } {
  mkdirSync(dirname(destPath), { recursive: true });
  writeFileSync(destPath, buildGeminiPolicyToml(), "utf8");
  return { path: destPath };
}
